### PR TITLE
created packages html with form and cards

### LINKED ISSUE #14: Packages Page - Include form that allows a user to add a package to the list of packages.
Hardcode form for now

### LINKED ISSUE #19: Create packages.html
https://www.figma.com/file/8vIX1yEXd2UxdWARbWqAje/GitSub?node-id=5%3A20

### LINKED ISSUE #47: Packages Page - Create a place for printed packages to go

### PR DESCRIPTION
**Pull request by cmeffley**
## Description
Created packages.html
Added Entry form
Modified cards slightly

## Related Issue
Fixes #19 
Fixes #14 
Fixes #47 

## Motivation and Context
Gives ability to enter data and put them somewhere

## How Can This Be Tested?
Form is added and cards are placed and smaller than cards previously used.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Review by jrobinson0529 — APPROVED** [review]
Looks great man 👍

**Comment by tsekeres** [comment]
Looks good 👍

**Comment by tsekeres** [comment]
My bad on the rereview.= for Jesse

**Review by jrobinson0529 — APPROVED** [review]

**Review by tsekeres — APPROVED** [review]
Looks good 👍

**Pull request merged**
