### PR TITLE
Jr profile bar styling

### PR DESCRIPTION
**Pull request by jrobinson0529**
## Description
Added some colors and styling for the profile sidebar. Formatted the files as well so they look pretty.
- Added a logo and input it across all hardcoded navbars
- Changed titles on each page to be consistent
- Moved images into an img folder and deleted redundancies and unused images.
- Added material icons CDN to all pages so profile icons would display properly.
- Formatted JS file
- Changed some redundancy in CSS that was overlapping styles on pages not intended.

## How Can This Be Tested?
Please test thoroughly as there are a lot of small changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Review by tsekeres — DISMISSED** [review]
Starting to look great! The About Me has issues. Background color on containers but not background?

**Review by caseywalker — APPROVED** [review]
Profile bar looks good! I see you fixed the alignment on the star, nice!

**Comment by tsekeres** [comment]
You've got old code in this now. Your branch has lost a lot of my code.

**Comment by tsekeres** [comment]
Works great. Small styling issues in Slack.

**Review by tsekeres — APPROVED** [review]

**Review by cmeffley — CHANGES_REQUESTED** [review]
The twitch tv link closes the about me section, everything else looks good to me.

**Review by cmeffley — APPROVED** [review]
👍

**Pull request merged**
