### PR TITLE
Jr pinned repo builder

### PR DESCRIPTION
**Pull request by jrobinson0529**
## Description
Added function for accept form input and building pinned repos page

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Review by cmeffley — COMMENTED** [review]
💯

**Review by cmeffley — APPROVED** [review]
💯

**Comment by jrobinson0529** [comment]
Not ready yet, waiting for data structure

**Review by caseywalker — APPROVED** [review]
🥇

**Pull request merged**
